version: '3.7'

services:
  mysql:
    image: mariadb:10.5
    restart: unless-stopped
    ports:
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=wygops
      - MYSQL_USER=wygops
      - MYSQL_PASSWORD=wygops
      - MYSQL_DATABASE=wygops
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8080:80
    links:
      - mysql:db
  ldap:
    image: cynt4k/wygops-ldap:latest
    build:
      context: scripts/docker
      dockerfile: ldap.Dockerfile
    environment: 
      - LDAP_ADMIN_PASSWORD=wygops
      - LDAP_BASE_DN=dc=wygops,dc=internal
    ports:
      - 389:389
  ldapadmin:
    image: osixia/phpldapadmin:stable
    ports:
      - 8081:80
    environment: 
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
      - PHPLDAPADMIN_HTTPS=false
    links: 
      - ldap
    