dev: false
general:
  subnet:
    v4: "192.168.9.0/24"
    v6: "fc00:cafe:c0d3::/64"
    gatewayV4: "192.168.9.1"
    gatewayV6: "fc00:cafe:c0d3::1"
  user:
    maxDevices: 3
  sync:
    interval: "5m"
wireguard:
  interface: "wg0"
database:
  host: localhost
  port: 3306
  username: wygops
  password: wygops
  database: wygops
provider:
  ldap:
    enabled: true
    type: "plain"
    host: "localhost"
    port: 389
    bindDn: "cn=admin,dc=wygops,dc=internal"
    bindPassword: "wygops"
    baseDn: "dc=wygops,dc=internal"
    userFilter: "(&(objectClass=inetOrgPerson))"
    groupFilter: "(|(objectClass=groupOfNames)(objectClass=groupOfUniqueNames))"
    userRdn: "cn"
    userAttr:
      - "cn"
      - "mail"
    groupAttr:
      - "cn"
    groupRdn: "cn"
api:
  host: "0.0.0.0"
  port: 3000
  jwt: 
    secret: b34afe530b019d7bb7f9b69ebe20b9725a01519743aa4e37d8a99b5304fa51a3
    lifetime: 2h
  