dev: false
general:
  subnet:
    v4: "172.20.0.0/16"
    v6: "fc00:cafe:c0d3::"
  user:
    maxDevices: 3
wireguard:
  privateKey: "MIM2pvpHqs0YYlXOrW9wKx/xyK2doN/fsptofEl9Y0g="
  publicKey: "pbTGR/v5EYUnXawHNRWyKg5vYMWe98WhU1DpQmmMXQw="
database:
  host: localhost
  port: 3306
  username: wygops
  password: wygops
  database: wygops
provider:
  ldap:
    enabled: true
    type: "plain"
    host: "localhost"
    port: 389
    bindDn: "cn=admin,dc=wygops,dc=internal"
    bindPassword: "wygops"
    baseDn: "dc=wygops,dc=internal"
    userFilter: "(&(objectClass=inetOrgPerson))"
    groupFilter: "(|(objectClass=groupOfNames)(objectClass=groupOfUniqueNames))"
    userRdn: "cn"
    userAttr:
      - "cn"
      - "mail"
    groupAttr:
      - "cn"
    groupRdn: "cn"
api:
  host: "0.0.0.0"
  port: 3000