// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package router

import (
	"github.com/cynt4k/wygops/internal/repository"
	"github.com/cynt4k/wygops/internal/router/v1"
	"github.com/cynt4k/wygops/internal/services"
	"github.com/jinzhu/gorm"
	"github.com/leandro-lugaresi/hub"
	"go.uber.org/zap"
)

// Injectors from router_wire.go:

func newRouter(hub2 *hub.Hub, db *gorm.DB, repo repository.Repository, ss *service.Services, logger *zap.Logger) *Router {
	engine := newGin(logger, repo)
	ldap := &ss.Ldap
	handlers := &v1.Handlers{
		Repo:   repo,
		Bus:    hub2,
		Logger: logger,
		User:   ldap,
	}
	router := &Router{
		app: engine,
		v1:  handlers,
	}
	return router
}
