// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package router

import (
	"github.com/cynt4k/wygops/cmd/config"
	"github.com/cynt4k/wygops/internal/repository"
	"github.com/cynt4k/wygops/internal/router/v1"
	"github.com/cynt4k/wygops/internal/services"
	"github.com/jinzhu/gorm"
	"github.com/leandro-lugaresi/hub"
	"go.uber.org/zap"
)

// Injectors from router_wire.go:

func newRouter(hub2 *hub.Hub, db *gorm.DB, repo repository.Repository, config2 *config.Config, ss *service.Services, logger *zap.Logger) *Router {
	echo := newEcho(logger, config2, repo)
	ldap := ss.Ldap
	wireguard := ss.Wireguard
	handlers := &v1.Handlers{
		Repo:      repo,
		Bus:       hub2,
		Logger:    logger,
		LDAP:      ldap,
		Wireguard: wireguard,
	}
	router := &Router{
		e:  echo,
		v1: handlers,
	}
	return router
}
